### ISSUE TITLE
Insegnamenti di Ingegneria informatica

### ISSUE THREAD

**Issue by foxyseta** [csunibo/csunibo.github.io#10]
Ne abbiamo già alcuni, e più di un ingegnere interessato. Appena dynamik è bello che è pronto possiamo aggiungerli.

**Comment by VaiTon** [comment]
Vedi:
- https://github.com/csunibo/ing-sistemi-operativi-t
- https://github.com/csunibo/ing-fondamenti-di-telecomunicazioni-t
- https://github.com/csunibo/ing-fisica-generale-t

**Comment by VaiTon** [comment]
Possiamo chiudere, aggiungiamo su richiesta le repo mancanti

**Comment by foxyseta** [comment]
Sono d'accordo. Grazie!
