### ISSUE TITLE
Rinnovamento pagina principale

### ISSUE THREAD

**Issue by foxyseta** [csunibo/csunibo.github.io#19]
La pagina principale di CSUnibo non dovrebbe più ora essere l'elenco degli insegnamenti su Statik (che fra l'altro è obsoleto). Dovrebbe essere una presentazione bilingue di CSUnibo (per strizzare l'occhio a chi studia AI) contenente i collegamenti a:
- [x] organizzazione GitHub
- [x] pagina principale delle raccolte delle risorse su Dynamik;
- [x] wiki;
- [x] canale Telegram;
- [x] modulo "CSUnibo in ascolto";
- [x] repository GitHub e istanze di altri progetti (modelli di tesi, bot, applicazioni web, web scraper).

Si può prendere ispirazione dal README del profilo di github.com/csunibo. Se non sono troppo invadente, mi piacerebbe dare un occhio attento ai contenuti e alla lingua.

Usiamo Hugo?

A lavoro fatto potrebbe essere bellino pubblicizzare con un comando `/csunibo` di Informabot, sul README del profilo di github.com/csunibo (che verrà svuotato) e scrivere un articolo sul blog di ADMStaff il cui ultimo post parla ancora dei laboratori chiusi per covid.

**Comment by musianisamuele** [comment]
Io sono favorevole all'uso di hugo

**Comment by lucat1** [comment]
Si con hugo c'è sicuramente un modo di generare la pagina con la lista dei corsi dal json, ci sta

**Comment by foxyseta** [comment]
Ah ma la lista dei corsi resta su Dynamik avevo capito

**Comment by ali-benny** [comment]
> scrivere un articolo sul blog di ADMStaff il cui ultimo post parla ancora dei laboratori chiusi per covid.

Per questo con @musianisamuele ci stavamo già mettendo in moto per aggiornarlo e inserire i nuovi contenuti

**Comment by ali-benny** [comment]
propongo questo tema https://themes.gohugo.io/themes/agnes-hugo-theme/

**Comment by musianisamuele** [comment]
Dobbiamo mettere il dark theme ma per il resto a me va bene

**Comment by ali-benny** [comment]
> Dobbiamo mettere il dark theme ma per il resto a me va bene

non si riesce a fare nero :D ne cerco un altro
