### ISSUE TITLE
Riorganizzare i progetti

### ISSUE THREAD

**Issue by foxyseta** [csunibo/csunibo.github.io#25]
Una nuova ripartizione dei progetti per includerli tutti in modo chiaro nella home potrebbe essere:

- materiale didattico (risorse)
- bot (Informabot)
- applicativi web (risorse, diario tirocinio, calendario)
- web scraper (descrizione unificata insegnamenti, raccoglitesi)
- modelli di tesi (latex, asciidoc, typst)
- strumenti interni (infrastruttura, synta, config, unibo-go, filenames-linter, upld, build-image, fileseeker, update, statik)

Lasciare anche la categoria "in via di sviluppo" proposta da @ali-benny mi sembra molto sensato: alcuni progetti apparterranno sia alla propria categoria che a quella.

Forse gli strumenti interni sono troppi e non andrebbero tutti sul sito?

Lista definitiva:

- [x] Web
- [x] Bot/Scraper
- [x] Tesi
- [x] Dipendenze
- [x] In arrivo

**Comment by ali-benny** [comment]
Personalmente eviterei categorie in cui è presente solo 1 elemento perché altrimenti avremmo troppe categorie e si perde il senso ,a mio parere. Però sono super d'accordissimo nel riorganizzarle e crearne di più appropriate.

Per modelli di tesi avevo fatto un'unica pagina così come era nella tabella del vecchio readme ma si può benissimo separare.

L'unica cosa è che "All" non si può togliere ecco...

**Comment by foxyseta** [comment]
Sì, è vero che categorie singoletto sono proprio ridicole. Il motivo per cui bot si trova lì in questo momento è che una volta ne esistevano tre (Telegram, Discord e csgitbot), ma gli altri due sono archiviati. Forse si possono accomunare bot e webscraper?

Risorse lo avevo messo da solo perché mi era parso avessi fatto così tu ma ho visto male. A rigor di logica, è un applicativo web al 100%.

Se facessimo così?

- tutti
- applicativi web (risorse, diario tirocinio, calendario)
- bot & web scraper (Informabot, descrizione unificata insegnamenti, raccoglitesi)
- modelli di tesi (latex, asciidoc, typst)
- strumenti interni (infrastruttura, synta, config, unibo-go, filenames-linter, upld, build-image, fileseeker, update, statik)
- lavori in corso

**Comment by ali-benny** [comment]
Perfetto, ultima piccola cosa AHAHHAHA se riuscissimo a trovare nomi non troppo lunghi, se no diventa una riga infinita, o chissene frega?

**Comment by foxyseta** [comment]
Sìsì figurati ci mancherebbe. Magari riscrivere le categorie citate sopra come (rispettivamente):

- Tutti
- Web
- Bot/Scraper
- Tesi
- Dipendenze
- In arrivo

?

**Comment by foxyseta** [comment]
Se ti va bene posso farlo anche io siccome sembra una cosa veloce.

**Comment by foxyseta** [comment]
Nessun problema. Ci mancherebbe. Hai già lavorato un sacco nelle scorse settimane!

**Comment by foxyseta** [comment]
Risolto con 06638ac. Se qualcosa non vi piace, cambiate pure senza problemi.
