### ISSUE TITLE
png -> svg

### ISSUE THREAD

**Issue by foxyseta** [csunibo/csunibo.github.io#33]
`assets/media/` e `img/` contengono immagini png del logo che andrebbero sostituite con un'unica svg (riusciamo a togliere anche le ico?). Va inoltre capito se servano le immagini in entrambe le cartelle o se ci siano residui pre-Hugo che non servono più.

Quindi idealmente avere una sola svg in una sola cartella con 0 png (e 0 ico?) e tutti i riferimenti nei file di configurazione aggiornati.

**Comment by LuigiBrosNin** [comment]
se ci sono problemi fatemi sapere, c'era poco da cambiare
